[package]
name = "terminal-company"
version = "0.1.0"
edition = "2024"

[dependencies]
lazy_static = "1.5.0"
mongodb = "3.3.0"
rand = "0.9.2"
serde = "1.0.219"
serde_json = "1.0.143"
tokio = "1.47.1"
dotenv = "0.15"
log = "0.4"
env_logger = "0.11"
crossterm = "0.29.0"
ratatui = "0.29.0"
